language: android

os:
  - linux

jdk:
  - oraclejdk8
  
android:
  components:
    - extra-android-m2repository
    - build-tools-23.0.1
    - android-23
  licenses:
    - android-sdk-license-.+

before_script:
 - chmod +x gradlew
